name: Tests
on: [push]
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./graphene_federation
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.6"
            architecture: x64

      - uses: actions/cache@v3
        id: pip-cache
        with:
            path: ${{ env.pythonLocation }}
            key: ${{ env.pythonLocation }}-pip-${{ hashFiles('**/Pipfile') }}

      - name: Install pipenv
        run: |
          pip install pipenv==2022.5.2
      - name: Install environment
        run: pipenv install --system --deploy --ignore-pipfile --dev

      - name: Run Unit Tests
        run: |
          make unittest
      - run: echo "🍏 This job's status is ${{ job.status }}."